### ISSUE TITLE
Magick::Image.from_blob TypeError: can't convert nil into String

### ISSUE THREAD

**Issue by jerodsanto** [amberbit/prawn-fast-png#1]
RMagick 2.11.0
prawn 0.5.0.1

@prawn_fast_png_data is being passed to Magick::Image.from_blob as **nil** which causes the TypeError on the method.

Maybe I don't understand how this is supposed to work, but it seems that setting the instance variable back to nil after running the aliased initialize will always cause this to be the case.

**Comment by wpiekutowski** [comment]
I was setting @prawn_fast_png_data to nil to not hog memory with image data after RGB and A chunks are separated. I haven't tested prawn-fast-png with prawn 0.5, but I guess there might have been some changes introduced to PNG handling that aren't compatible with prawn-fast-png.

Please provide a small code snippet which reproduces the issue.

**Comment by jerodsanto** [comment]
Looks like removing the line that sets @prawn_fast_png_data to nil fixes the problem for now, as you can see in my fork. Perhaps there is a more efficient way of solving the problem though?

A code snippet that reproduces the issue:

```
require 'prawn'
require 'prawn/fast_png'

pdf = Prawn::Document.new
pdf.image 'dice.png'
pdf.render_file 'example.pdf'
```

**Comment by wpiekutowski** [comment]
I've moved the nil assignment to #unfilter_image_data and this fixes the incompatibility. A new gem is available through github.

Thanks for reporting this.
